---
server:
  port: 8080
---
spring:
  profiles: svil,default
datasource:
  servizidipendenti:
    url: jdbc:mysql://localhost:3306/servizidipendenti
    username: root
    password: administrator
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect